[window]
dimensions = { columns = 100, lines = 28 }
padding = { x = 8, y = 8 }
decorations = "full"
#decorations = "none"
opacity = 1.0
blur = true

[font]
normal = { family = "Cascadia Code", style = "Regular" }
bold = { family = "Cascadia Code", style = "Bold" }
italic = { family = "Cascadia Code", style = "Italic" }
size = 11.0

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
